# @package _global_
# Task go1-stairs-terrain-walk: rslrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: rslrl.ppo
  - _self_
task:
  env: go1-stairs-terrain-walk
  rllib: rslrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  max_iterations: 1000
  actor:
    hidden_dims:
      - 512
      - 256
      - 128
  critic:
    hidden_dims:
      - 512
      - 256
      - 128
  algorithm:
    num_mini_batches: 3
