defaults:
  - export_deploy_schema
  - _self_
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

env: null
run: null
output: null
validation:
  seed: 1
  samples: 32
  atol: 1e-5
  rtol: 1e-5
