# @package _global_
# Task anymal_c_navigation_flat: rslrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: rslrl.ppo
  - _self_
task:
  env: anymal_c_navigation_flat
  rllib: rslrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  num_steps_per_env: 48
  max_iterations: 1017
  algorithm:
    num_learning_epochs: 6
