# @package _global_
# Task point_mass: skrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: skrl.ppo
  - _self_
task:
  env: point_mass
  rllib: skrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  models:
    value:
      hiddens:
        - 32
        - 32
    policy:
      hiddens:
        - 32
        - 32
  agent:
    mini_batches: 4
