# @package _global_
# Task cartpole: skrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: skrl.ppo
  - _self_
task:
  env: cartpole
  rllib: skrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  models:
    policy:
      hiddens:
        - 32
        - 32
    value:
      hiddens:
        - 32
        - 32
  agent:
    learning_epochs: 5
    mini_batches: 4
  trainer:
    timesteps: 5000
