# @package _global_
# Task dm-hopper-stand: skrl.ppo, train_backend=torch delta.
defaults:
  - /task/dm-hopper-stand/skrl.ppo@_global_
  - _self_
task:
  train_backend: torch
algo:
  agent:
    learning_epochs: 5
