# @package _global_
# Task dm-quadruped-escape: rslrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: rslrl.ppo
  - _self_
task:
  env: dm-quadruped-escape
  rllib: rslrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  max_iterations: 1667
  algorithm:
    learning_rate: 0.0002
    num_learning_epochs: 4
    num_mini_batches: 32
