defaults:
  - _self_
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ${hydra.job.num}
  job:
    chdir: false

artifact: ???
backend: ???
viewer: ???
