# @package _global_
# Task dm-quadruped-walk: skrl.ppo, train_backend=torch delta.
defaults:
  - /task/dm-quadruped-walk/skrl.ppo@_global_
  - _self_
task:
  train_backend: torch
algo:
  trainer:
    timesteps: 27000
