# @package _global_
# Task dm-cheetah: skrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: skrl.ppo
  - _self_
task:
  env: dm-cheetah
  rllib: skrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  agent:
    rollouts: 24
    learning_epochs: 4
    learning_rate: 0.0002
  trainer:
    timesteps: 20000
