# @package _global_
# Task rm65-open-cabinet: rslrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: rslrl.ppo
  - _self_
task:
  env: rm65-open-cabinet
  rllib: rslrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 64
algo:
  max_iterations: 1500
  algorithm:
    num_mini_batches: 8
    entropy_coef: 0.001
