# @package _global_
# Task dm-humanoid-stand: skrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: skrl.ppo
  - _self_
task:
  env: dm-humanoid-stand
  rllib: skrl
  algo: ppo
  train_backend: null
num_envs: 2048
play_num_envs: 16
seed: 42
algo:
  models:
    value:
      hiddens:
        - 512
        - 256
        - 128
    policy:
      hiddens:
        - 512
        - 256
        - 128
  agent:
    rollouts: 24
    mini_batches: 2
    learning_rate: 0.0003
    learning_epochs: 8
  trainer:
    timesteps: 20000
