# @package _global_
# Task shadow-hand-repose: skrl.ppo shared training recipe.
defaults:
  - /algo_base@algo: skrl.ppo
  - _self_
task:
  env: shadow-hand-repose
  rllib: skrl
  algo: ppo
  train_backend: null
num_envs: 8192
play_num_envs: 16
seed: 42
algo:
  models:
    policy:
      hiddens:
        - 512
        - 512
        - 256
        - 128
    value:
      hiddens:
        - 512
        - 512
        - 256
        - 128
  agent:
    rollouts: 16
    learning_epochs: 5
    mini_batches: 4
    learning_rate: 0.0005
    learning_rate_scheduler_kwargs:
      kl_threshold: 0.016
    rewards_shaper_scale: 0.01
    time_limit_bootstrap: false
  trainer:
    timesteps: 24000
